create table permissions (permission_id bigint generated by default as identity, permission_name varchar(255), primary key (permission_id));
create table role_permissions (role_id integer not null, permission_id bigint not null, primary key (role_id, permission_id));
create table roles (role_id integer generated by default as identity, role_name varchar(255), primary key (role_id));
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id));
create table users (user_id bigint generated by default as identity, enabled boolean, password varchar(255), username varchar(255), primary key (user_id));
create table todo (id bigint not null, completed varchar(255), todo_item varchar(255), primary key (id));
